#!/usr/bin/env bash
set -eux

native_image=$JAVA_HOME/bin/native-image

mkdir -p target

${native_image} \
    -H:+PrintClassInitialization \
    -H:BuildOutputJSONFile=target/build-output-layer-base.json \
    -H:LayerCreate=libnettybaselayer.nil,module=java.base,module=jdk.localedata,package=io.netty.* \
    -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager \
    --initialize-at-build-time="" \
    --initialize-at-run-time=io.netty.buffer.AbstractReferenceCountedByteBuf \
    --initialize-at-run-time=io.netty.buffer.ByteBufAllocator \
    --initialize-at-run-time=io.netty.buffer.ByteBufUtil \
    --initialize-at-run-time=io.netty.buffer.ByteBufUtil\$HexUtil \
    --initialize-at-run-time=io.netty.buffer.PooledByteBufAllocator \
    --initialize-at-run-time=io.netty.buffer.Unpooled \
    --initialize-at-run-time=io.netty.buffer.UnpooledByteBufAllocator \
    --initialize-at-run-time=io.netty.channel.DefaultChannelId \
    --initialize-at-run-time=io.netty.channel.unix.Errors \
    --initialize-at-run-time=io.netty.channel.unix.FileDescriptor \
    --initialize-at-run-time=io.netty.channel.unix.IovArray \
    --initialize-at-run-time=io.netty.channel.unix.Limits \
    --initialize-at-run-time=io.netty.handler.codec.ReplayingDecoderByteBuf \
    --initialize-at-run-time=io.netty.handler.codec.compression.BrotliDecoder \
    --initialize-at-run-time=io.netty.handler.codec.compression.BrotliOptions \
    --initialize-at-run-time=io.netty.handler.codec.compression.ZstdConstants \
    --initialize-at-run-time=io.netty.handler.codec.compression.ZstdOptions \
    --initialize-at-run-time=io.netty.handler.codec.http.HttpObjectAggregator \
    --initialize-at-run-time=io.netty.handler.codec.http.HttpObjectEncoder \
    --initialize-at-run-time=io.netty.handler.codec.http.HttpServerExpectContinueHandler \
    --initialize-at-run-time=io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder \
    --initialize-at-run-time=io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder \
    --initialize-at-run-time=io.netty.handler.codec.http2.CleartextHttp2ServerUpgradeHandler \
    --initialize-at-run-time=io.netty.handler.codec.http2.DefaultHttp2FrameWriter \
    --initialize-at-run-time=io.netty.handler.codec.http2.Http2ClientUpgradeCodec \
    --initialize-at-run-time=io.netty.handler.codec.http2.Http2CodecUtil \
    --initialize-at-run-time=io.netty.handler.codec.http2.Http2ConnectionHandler \
    --initialize-at-run-time=io.netty.handler.pcap.PcapWriteHandler\$WildcardAddressHolder \
    --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils \
    --initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine \
    --initialize-at-run-time=io.netty.handler.ssl.JdkSslServerContext \
    --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext \
    --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine \
    --initialize-at-run-time=io.netty.handler.ssl.util.ThreadLocalInsecureRandom \
    --initialize-at-run-time=io.netty.resolver.HostsFileEntriesResolver \
    --initialize-at-run-time=io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider \
    --initialize-at-run-time=io.netty.resolver.dns.DnsNameResolver \
    --initialize-at-run-time=io.netty.resolver.dns.DnsNameResolverBuilder \
    --initialize-at-run-time=io.netty.resolver.dns.DnsServerAddressStreamProviders\$DefaultProviderHolder \
    --initialize-at-run-time=io.netty.resolver.dns.ResolvConf\$ResolvConfLazy \
    --initialize-at-run-time=io.netty.util.AbstractReferenceCounted \
    --initialize-at-run-time=io.netty.util.NetUtil \
    --initialize-at-run-time=io.netty.util.NetUtilSubstitutions\$NetUtilLocalhost4LazyHolder \
    --initialize-at-run-time=io.netty.util.NetUtilSubstitutions\$NetUtilLocalhost6LazyHolder \
    --initialize-at-run-time=io.netty.util.NetUtilSubstitutions\$NetUtilLocalhostLazyHolder \
    --initialize-at-run-time=io.smallrye.common.os.Process \
    --initialize-at-run-time=io.smallrye.common.net.HostName \
    --initialize-at-run-time=io.smallrye.common.ref.References\$ReaperThread \
    --initialize-at-run-time=io.quarkus.netty.runtime.EmptyByteBufStub \
    --initialize-at-run-time=io.quarkus.runtime.graal.InetRunTime \
    --initialize-at-run-time=java.rmi \
    --initialize-at-run-time=sun.rmi \
    --initialize-at-run-time=org.jboss.threads.JDKSpecific\$ThreadAccess \
    --initialize-at-run-time=org.jboss.logmanager.handlers.ConsoleHandler\$ConsoleHolder \
    --initialize-at-run-time=org.jboss.logmanager.handlers.SyslogHandler \
    --initialize-at-run-time=jdk.tools.jlink.internal.plugins \
    --initialize-at-run-time=jdk.jpackage.internal.LinuxPackageArch\$DebPackageArch \
    --initialize-at-run-time=jdk.jpackage.internal.LinuxPackageArch\$RpmPackageArch \
    -cp $(echo \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/modified-io.netty.*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/com.aayushatharva.brotli4j.*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.quarkus.quarkus-core-999-SNAPSHOT.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.quarkus.quarkus-netty-999-SNAPSHOT.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.quarkus.quarkus-bootstrap-runner-999-SNAPSHOT.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.quarkus.quarkus-classloader-commons-999-SNAPSHOT.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.smallrye.common.smallrye-common-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.smallrye.config.smallrye-config-core-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.smallrye.config.smallrye-config-common-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/org.jboss.logmanager.jboss-logmanager-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/org.jboss.logging.jboss-logging-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/org.jboss.threads.jboss-threads-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/org.slf4j.slf4j-api-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/org.wildfly.common.wildfly-common-*.jar \
        getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/org.eclipse.microprofile.config.microprofile-config-api-*.jar \
        | tr ' ' ':') \
    -o libnettybaselayer -H:Path=./target
