app := code-with-quarkus

NB_ARGS := -H:+UseNewExperimentalClassInitialization

default: run

include ../make/common/MakeBase.gmk
include ../make/common/Maven.gmk
include ../make/common/QuarkusBase.gmk

java_home := /opt/graalvm-ce-java17-22.3.0
quarkus_version := 3.0.1.Final
