APP ?= getting-started
QUICKSTARTS_BRANCH ?= development

java_home := /opt/graalvm-ce-java17-22.3.0

default: run

include ../make/common/MakeBase.gmk
include ../make/common/Podman.gmk
include ../make/common/Maven.gmk
include ../make/common/QuarkusQuick.gmk
include ../make/common/QuarkusDev.gmk
