app := getting-started
java_home := /opt/graalvm-ce-java17-22.3.0
quarkus_version := 999-SNAPSHOT
quickstarts_branch := development

default: run

include ../make/common/MakeBase.gmk
include ../make/common/Podman.gmk
include ../make/common/Maven.gmk
include ../make/common/QuarkusQuick.gmk
include ../make/common/QuarkusDev.gmk
