FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10

ARG RHSM_USERNAME
ARG RHSM_PASSWORD

RUN microdnf install -y subscription-manager \
  && subscription-manager register \
    --username="${RHSM_USERNAME}" \
    --password="${RHSM_PASSWORD}" \
    --auto-attach \
  && subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-source-rpms \
  && microdnf install -y perf \
  && microdnf clean all
