app := getting-started
java_home := /opt/java-17
quarkus_version := 2.16.999-SNAPSHOT
quickstarts_branch := 2.16

default: build-quarkus run-jvm

include ../make/common/MakeBase.gmk
include ../make/common/Maven.gmk
include ../make/common/QuarkusQuick.gmk
include ../make/common/QuarkusDev.gmk
