default: run

include ../make/common/MakeBase.gmk
include ../make/common/Maven.gmk
include ../make/common/QuarkusApp.gmk
include ../make/common/Hyperfoil.gmk

extensions := resteasy-reactive
java_home := /opt/graalvm-ce-java17-22.3.0
quarkus_version := 3.0.1.Final
