include ../make/common/MakeBase.gmk
include ../make/common/QuarkusApp.gmk
include ../make/common/Maven.gmk

extensions := resteasy-reactive
java_home := /opt/graalvm-ce-java17-22.3.0
quarkus_version := 2.16.5.Final
