#!/usr/bin/env bash
set -eux

BASE_NATIVE_ARGS=()

#BASE_NATIVE_ARGS=(
#    "-J-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
#    "-J-Dsun.nio.ch.maxUpdateArraySize=100"
#    "-J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory"
#    "-J-Dvertx.disableDnsResolver=true"
#    "-J-Dio.netty.tryReflectionSetAccessible=true"
#    "-J-Dio.netty.noUnsafe=true"
#    "-J-Dio.netty.leakDetection.level=DISABLED"
#    "-J-Dio.netty.allocator.maxOrder=3"
#    "-J-Duser.language=en"
#    "-J-Dlogging.initial-configurator.min-level=500" "-H:+UnlockExperimentalVMOptions"
#    "-H:IncludeLocales=en" "-H:-UnlockExperimentalVMOptions"
#    "--enable-native-access=ALL-UNNAMED"
#    "-J-Dfile.encoding=UTF-8"
#    "-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED"
#    # todo: move io.quarkus.runner.Feature to app layer
#    "--features=io.quarkus.runtime.graal.DisableLoggingFeature,io.quarkus.runtime.graal.JVMChecksFeature,io.quarkus.runtime.graal.SkipConsoleServiceProvidersFeature"
#    "-J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED"
#    "-J--add-exports=java.security.jgss/sun.security.jgss=ALL-UNNAMED"
#    "-J--add-opens=java.base/java.text=ALL-UNNAMED"
#    "-J--add-opens=java.base/java.io=ALL-UNNAMED"
#    "-J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED"
#    "-J--add-opens=java.base/java.util=ALL-UNNAMED" "-H:+UnlockExperimentalVMOptions"
#    "-H:BuildOutputJSONFile=getting-started-1.0.0-SNAPSHOT-runner-build-output-stats.json" "-H:-UnlockExperimentalVMOptions" "-H:+UnlockExperimentalVMOptions"
#    "-H:+GenerateBuildArtifactsFile" "-H:-UnlockExperimentalVMOptions"
#    "-H:+PrintClassInitialization"
#    "-H:-CheckToolchain" "-H:+UnlockExperimentalVMOptions"
#    "-H:+AllowFoldMethods" "-H:-UnlockExperimentalVMOptions" "-H:+UnlockExperimentalVMOptions"
#    "-H:+SharedArenaSupport" "-H:-UnlockExperimentalVMOptions"
#    "-J-Djava.awt.headless=true"
#    "--link-at-build-time" "-H:+UnlockExperimentalVMOptions"
#    "-H:+ReportExceptionStackTraces" "-H:-UnlockExperimentalVMOptions"
#    "-H:-AddAllCharsets"
#    "--enable-url-protocols=http"
#    "-H:NativeLinkerOption=-no-pie"
#    "--enable-monitoring=heapdump,threaddump" "-H:+UnlockExperimentalVMOptions"
#    "-H:-UseServiceLoaderFeature" "-H:-UnlockExperimentalVMOptions"
#    "--exclude-config" 'io\.netty\.netty-codec.*' '/META-INF/native-image/io\.netty/netty-codec.*/generated/handlers/reflect-config\.json'
#    "--exclude-config" 'io\.netty\.netty-handler' '/META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json'
#)

#LAYERED_NATIVE_ARGS=(
#    "--initialize-at-run-time=io.netty.channel.unix.Errors"
#    "--initialize-at-run-time=io.netty.channel.unix.FileDescriptor"
#    "--initialize-at-run-time=io.netty.channel.unix.IovArray"
#    "--initialize-at-run-time=io.netty.channel.unix.Limits"
#    "--initialize-at-run-time=io.netty.handler.codec.compression.BrotliDecoder"
#    "--initialize-at-run-time=io.netty.handler.codec.compression.BrotliOptions"
#    "--initialize-at-run-time=io.netty.handler.codec.compression.Lz4XXHash32"
#    "--initialize-at-run-time=io.netty.handler.codec.compression.ZstdConstants"
#    "--initialize-at-run-time=io.netty.handler.codec.compression.ZstdOptions"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.BoringSSL"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.BoringSSLAsyncPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.InsecureQuicTokenHandler"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.Quiche"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.QuicConnectionAddress"
#    "--initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils"
#    "--initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine"
#    "--initialize-at-run-time=io.netty.handler.ssl.JdkSslServerContext"
#    "--initialize-at-run-time=io.netty.handler.ssl.OpenSslAsyncPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.handler.ssl.OpenSslPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext"
#    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine"
#    "--initialize-at-run-time=io.netty.handler.ssl.util.ThreadLocalInsecureRandom"
#    "--initialize-at-run-time=io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.internal.tcnative.CertificateCompressionAlgo"
#    "--initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSL"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSLContext"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSLPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSLSession"
#    "--initialize-at-run-time=io.smallrye.common.net.HostName"
#    "--initialize-at-run-time=io.quarkus.runtime.graal.InetRunTime"
#    "--initialize-at-build-time=\"\""
#    "-H:LayerCreate=libquarkusbaselayer.nil,module=java.base,module=jdk.localedata,package=io.quarkus.*,package=io.netty.*,package=io.vertx.*,package=jakarta.*"
#    "-cp" "getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/*"
#    "-o" "libquarkusbaselayer"
#    "-H:Path=./target"
#)

#LAYERED_NATIVE_ARGS=(
#    "--initialize-at-run-time=io.netty.bootstrap.AbstractBootstrap"
#    "--initialize-at-run-time=io.netty.bootstrap.Bootstrap"
#    "--initialize-at-run-time=io.netty.bootstrap.ServerBootstrap"
#    "--initialize-at-run-time=io.netty.buffer.AbstractByteBuf"
#    "--initialize-at-run-time=io.netty.buffer.AbstractByteBufAllocator"
#    "--initialize-at-run-time=io.netty.buffer.AdaptivePoolingAllocator"
#    "--initialize-at-run-time=io.netty.channel.AbstractChannel"
#    "--initialize-at-run-time=io.netty.channel.AbstractChannelHandlerContext"
#    "--initialize-at-run-time=io.netty.channel.AbstractCoalescingBufferQueue"
#    "--initialize-at-run-time=io.netty.channel.DefaultChannelId"
#    "--initialize-at-run-time=io.netty.channel.DefaultChannelPipeline"
#    "--initialize-at-run-time=io.netty.channel.local.LocalChannel"
#    "--initialize-at-run-time=io.netty.channel.unix.Errors"
#    "--initialize-at-run-time=io.netty.channel.unix.FileDescriptor"
#    "--initialize-at-run-time=io.netty.channel.unix.IovArray"
#    "--initialize-at-run-time=io.netty.channel.unix.Limits"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.BoringSSL"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.BoringSSLAsyncPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.InsecureQuicTokenHandler"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.Quiche"
#    "--initialize-at-run-time=io.netty.handler.codec.quic.QuicConnectionAddress"
#    "--initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils"
#    "--initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine"
#    "--initialize-at-run-time=io.netty.handler.ssl.JdkSslServerContext"
#    "--initialize-at-run-time=io.netty.handler.ssl.OpenSslAsyncPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.handler.ssl.OpenSslPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext"
#    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine"
#    "--initialize-at-run-time=io.netty.handler.ssl.SslUtils"
#    "--initialize-at-run-time=io.netty.handler.ssl.util.ThreadLocalInsecureRandom"
#    "--initialize-at-run-time=io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.internal.tcnative.CertificateCompressionAlgo"
#    "--initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSL"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSLContext"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSLPrivateKeyMethod"
#    "--initialize-at-run-time=io.netty.internal.tcnative.SSLSession"
#    "--initialize-at-run-time=io.netty.util.concurrent.PromiseNotifier"
#    "--initialize-at-run-time=io.netty.util.concurrent.SingleThreadEventExecutor"
#    "--initialize-at-run-time=io.netty.util.internal.PlatformDependent"
#    "--initialize-at-run-time=io.netty.util.internal.PlatformDependent0"
#    "--initialize-at-run-time=io.netty.util.internal.RefCnt"
#    "--initialize-at-run-time=io.smallrye.common.net.HostName"
#    "--initialize-at-run-time=io.smallrye.common.net.Inet"
#    "--initialize-at-run-time=io.quarkus.runtime.graal.InetRunTime"
#    "--initialize-at-build-time=\"\""
#    "-H:LayerCreate=libquarkusbaselayer.nil,module=java.base,module=jdk.localedata,package=io.quarkus.*,package=io.netty.*,package=io.vertx.*,package=jakarta.*"
#    "-cp" "getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/*"
#    "-o" "libquarkusbaselayer"
#    "-H:Path=./target"
#)

# Adapted from quarkus-base experiment
RUN_INIT_NATIVE_ARGS=(
    "--initialize-at-run-time=io.netty.buffer.AbstractByteBuf"
    "--initialize-at-run-time=io.netty.buffer.AbstractByteBufAllocator"
    "--initialize-at-run-time=io.netty.buffer.AdaptivePoolingAllocator"
    "--initialize-at-run-time=io.netty.buffer.AdaptivePoolingAllocator\$Magazine"
    "--initialize-at-run-time=io.netty.buffer.AdvancedLeakAwareByteBuf"
    "--initialize-at-run-time=io.netty.buffer.EmptyByteBuf"
    "--initialize-at-run-time=io.netty.buffer.PoolThreadCache"
    "--initialize-at-run-time=io.netty.channel.AbstractChannel"
    "--initialize-at-run-time=io.netty.channel.AbstractChannelHandlerContext"
    "--initialize-at-run-time=io.netty.channel.AbstractCoalescingBufferQueue"
    "--initialize-at-run-time=io.netty.channel.ChannelHandlerMask"
    "--initialize-at-run-time=io.netty.channel.DefaultChannelId"
    "--initialize-at-run-time=io.netty.channel.DefaultChannelPipeline"
    "--initialize-at-run-time=io.netty.channel.MultithreadEventLoopGroup"
    "--initialize-at-run-time=io.netty.util.concurrent.AbstractEventExecutor"
    "--initialize-at-run-time=io.netty.util.concurrent.DefaultPromise"
    "--initialize-at-run-time=io.netty.util.concurrent.PromiseNotifier"
    "--initialize-at-run-time=io.netty.util.concurrent.SingleThreadEventExecutor"
    "--initialize-at-run-time=io.netty.util.concurrent.FastThreadLocalThread"
    "--initialize-at-run-time=io.netty.bootstrap.AbstractBootstrap"
    "--initialize-at-run-time=io.netty.bootstrap.Bootstrap"
    "--initialize-at-run-time=io.netty.bootstrap.ServerBootstrap"
    "--initialize-at-run-time=io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod"
    "--initialize-at-run-time=io.netty.internal.tcnative.CertificateCompressionAlgo"
    "--initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier"
    "--initialize-at-run-time=io.netty.internal.tcnative.SSL"
    "--initialize-at-run-time=io.netty.internal.tcnative.SSLContext"
    "--initialize-at-run-time=io.netty.internal.tcnative.SSLPrivateKeyMethod"
    "--initialize-at-run-time=io.netty.internal.tcnative.SSLSession"
    "--initialize-at-run-time=io.netty.channel.DefaultChannelId"
    "--initialize-at-run-time=io.netty.channel.unix.Errors"
    "--initialize-at-run-time=io.netty.channel.unix.FileDescriptor"
    "--initialize-at-run-time=io.netty.channel.unix.IovArray"
    "--initialize-at-run-time=io.netty.channel.unix.Limits"
    "--initialize-at-run-time=io.netty.handler.codec.http.HttpServerExpectContinueHandler"
    "--initialize-at-run-time=io.netty.handler.codec.http2"
    # "--initialize-at-run-time=io.netty.handler.codec.http2.CleartextHttp2ServerUpgradeHandler"
    "--initialize-at-run-time=io.netty.handler.codec.quic.BoringSSL"
    "--initialize-at-run-time=io.netty.handler.codec.quic.BoringSSLAsyncPrivateKeyMethod"
    "--initialize-at-run-time=io.netty.handler.codec.quic.InsecureQuicTokenHandler"
    "--initialize-at-run-time=io.netty.handler.codec.quic.Quiche"
    "--initialize-at-run-time=io.netty.handler.codec.quic.QuicConnectionAddress"
    "--initialize-at-run-time=io.netty.handler.pcap.PcapWriteHandler\$WildcardAddressHolder"
    "--initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils"
    "--initialize-at-run-time=io.netty.util.internal.PlatformDependent"
    "--initialize-at-run-time=io.netty.util.internal.PlatformDependent0"
    "--initialize-at-run-time=io.netty.util.internal.RefCnt"
    "--initialize-at-run-time=io.netty.util.ReferenceCountUtil"
    "--initialize-at-run-time=io.netty.util.NetUtil"
    "--initialize-at-run-time=io.quarkus.netty.runtime.EmptyByteBufStub"
    "--initialize-at-run-time=io.quarkus.runtime.configuration.RuntimeConfigBuilder\$UuidConfigSource\$Holder"
    "--initialize-at-run-time=io.quarkus.runtime.graal.InetRunTime"
    "--initialize-at-run-time=io.quarkus.runtime.ExecutorRecorder"
    "--initialize-at-run-time=io.vertx.core.buffer.impl.PartialPooledByteBufAllocator"
    "--initialize-at-run-time=io.vertx.core.buffer.impl.VertxByteBufAllocator"
    "--initialize-at-run-time=io.vertx.core.eventbus.impl.clustered.ClusteredEventBus"
    "--initialize-at-run-time=io.vertx.ext.auth.impl.jose.JWT"
    "--initialize-at-run-time=jakarta.el.ELManager"
    "--initialize-at-run-time=java.rmi"
    "--initialize-at-run-time=java.util.logging.ConsoleHandler"
    "--initialize-at-run-time=jdk.jpackage.internal.LinuxPackageArch\$DebPackageArch"
    "--initialize-at-run-time=jdk.jpackage.internal.LinuxPackageArch\$RpmPackageArch"
    "--initialize-at-run-time=jdk.package"
    "--initialize-at-run-time=jdk.tools.jlink.internal.plugins"
    "--initialize-at-run-time=org.jboss.threads.JDKSpecific\$ThreadAccess"
    "--initialize-at-run-time=org.jboss.logging.JDKLevel"
    "--initialize-at-run-time=org.jboss.logmanager.handlers.ConsoleHandler\$ConsoleHolder"
    "--initialize-at-run-time=org.jboss.logmanager.handlers.SyslogHandler"
    "--initialize-at-run-time=org.jboss.logmanager.Level"
    "--initialize-at-run-time=sun.rmi"
    "--initialize-at-run-time=io.smallrye.common.os.Process"
    "--initialize-at-run-time=io.smallrye.common.net.HostName"
    "--initialize-at-run-time=io.vertx.core.http.impl.Http1xServerResponse"
    "--initialize-at-run-time=io.vertx.core.http.impl.VertxHttp2ClientUpgradeCodec"
    "--initialize-at-run-time=io.vertx.core.parsetools.impl.RecordParserImpl"
    "--initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine"
    "--initialize-at-run-time=io.netty.handler.ssl.OpenSslAsyncPrivateKeyMethod"
    "--initialize-at-run-time=io.netty.handler.ssl.OpenSslPrivateKeyMethod"
    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine"
    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext"
    "--initialize-at-run-time=io.netty.handler.ssl.JdkSslServerContext"
    "--initialize-at-run-time=io.netty.handler.ssl.util.ThreadLocalInsecureRandom"
    "--initialize-at-run-time=io.netty.handler.codec.http.HttpObjectEncoder"
    "--initialize-at-run-time=io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder"
    "--initialize-at-run-time=io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder"
    "--initialize-at-run-time=io.netty.handler.codec.http2.Http2CodecUtil"
    "--initialize-at-run-time=io.netty.handler.codec.http2.DefaultHttp2FrameWriter"
    "--initialize-at-run-time=io.netty.handler.codec.http2.Http2ConnectionHandler"
    "--initialize-at-run-time=io.netty.handler.codec.http2.Http2ClientUpgradeCodec"
    "--initialize-at-run-time=io.netty.util.AbstractReferenceCounted"
    "--initialize-at-run-time=io.netty.buffer.AbstractReferenceCountedByteBuf"
    "--initialize-at-run-time=io.netty.buffer.UnpooledByteBufAllocator"
    "--initialize-at-run-time=io.netty.buffer.Unpooled"
    "--initialize-at-run-time=io.netty.handler.codec.http.HttpObjectAggregator"
    "--initialize-at-run-time=io.netty.handler.codec.ReplayingDecoderByteBuf"
    "--initialize-at-run-time=io.netty.buffer.ByteBufUtil\$HexUtil"
    "--initialize-at-run-time=io.netty.buffer.PooledByteBufAllocator"
    "--initialize-at-run-time=io.netty.buffer.ByteBufAllocator"
    "--initialize-at-run-time=io.netty.buffer.ByteBufUtil"
    "--initialize-at-run-time=io.netty.handler.codec.compression.BrotliOptions"
    "--initialize-at-run-time=io.netty.handler.codec.compression.ZstdConstants"
    "--initialize-at-run-time=io.netty.handler.codec.compression.ZstdOptions"
    "--initialize-at-run-time=io.vertx.ext.web.handler.sockjs.impl.XhrTransport"
    "--initialize-at-run-time=io.netty.channel.DefaultChannelId"
    "--initialize-at-run-time=io.netty.channel.unix.Errors"
    "--initialize-at-run-time=io.netty.channel.unix.FileDescriptor"
    "--initialize-at-run-time=io.netty.channel.unix.IovArray"
    "--initialize-at-run-time=io.netty.channel.unix.Limits"
    "--initialize-at-run-time=io.netty.handler.codec.http.HttpServerExpectContinueHandler"
    "--initialize-at-run-time=io.netty.handler.codec.http2.CleartextHttp2ServerUpgradeHandler"
    "--initialize-at-run-time=io.netty.handler.pcap.PcapWriteHandler\$WildcardAddressHolder"
    "--initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils"
    "--initialize-at-run-time=io.netty.util.internal.PlatformDependent"
    "--initialize-at-run-time=io.netty.util.internal.PlatformDependent0"
    "--initialize-at-run-time=io.netty.util.NetUtil"
    "--initialize-at-run-time=io.quarkus.netty.runtime.EmptyByteBufStub"
    "--initialize-at-run-time=io.quarkus.runtime.configuration.RuntimeConfigBuilder\$UuidConfigSource\$Holder"
    "--initialize-at-run-time=io.quarkus.runtime.graal.InetRunTime"
    "--initialize-at-run-time=io.quarkus.runtime.ExecutorRecorder"
    "--initialize-at-run-time=io.vertx.core.buffer.impl.PartialPooledByteBufAllocator"
    "--initialize-at-run-time=io.vertx.core.buffer.impl.VertxByteBufAllocator"
    "--initialize-at-run-time=io.vertx.core.eventbus.impl.clustered.ClusteredEventBus"
    "--initialize-at-run-time=io.vertx.ext.auth.impl.jose.JWT"
    "--initialize-at-run-time=jakarta.el.ELManager"
    "--initialize-at-run-time=java.rmi"
    "--initialize-at-run-time=java.util.logging.ConsoleHandler"
    "--initialize-at-run-time=jdk.jpackage.internal.LinuxPackageArch\$DebPackageArch"
    "--initialize-at-run-time=jdk.jpackage.internal.LinuxPackageArch\$RpmPackageArch"
    "--initialize-at-run-time=jdk.package"
    "--initialize-at-run-time=jdk.tools.jlink.internal.plugins"
    "--initialize-at-run-time=org.jboss.threads.JDKSpecific\$ThreadAccess"
    "--initialize-at-run-time=org.jboss.logmanager.handlers.ConsoleHandler\$ConsoleHolder"
    "--initialize-at-run-time=org.jboss.logmanager.handlers.SyslogHandler"
    "--initialize-at-run-time=sun.rmi"
    "--initialize-at-run-time=io.smallrye.common.os.Process"
    "--initialize-at-run-time=io.smallrye.common.net.HostName"
    "--initialize-at-run-time=io.smallrye.common.net.INet"
    "--initialize-at-run-time=io.vertx.core.http.impl.Http1xServerResponse"
    "--initialize-at-run-time=io.vertx.core.http.impl.VertxHttp2ClientUpgradeCodec"
    "--initialize-at-run-time=io.vertx.core.parsetools.impl.RecordParserImpl"
    "--initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine"
    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine"
    "--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext"
    "--initialize-at-run-time=io.netty.handler.ssl.JdkSslServerContext"
    "--initialize-at-run-time=io.netty.handler.ssl.util.ThreadLocalInsecureRandom"
    "--initialize-at-run-time=io.netty.handler.codec.http.HttpObjectEncoder"
    "--initialize-at-run-time=io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder"
    "--initialize-at-run-time=io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder"
    "--initialize-at-run-time=io.netty.handler.codec.http2.Http2CodecUtil"
    "--initialize-at-run-time=io.netty.handler.codec.http2.DefaultHttp2FrameWriter"
    "--initialize-at-run-time=io.netty.handler.codec.http2.Http2ConnectionHandler"
    "--initialize-at-run-time=io.netty.handler.codec.http2.Http2ClientUpgradeCodec"
    "--initialize-at-run-time=io.netty.util.AbstractReferenceCounted"
    "--initialize-at-run-time=io.netty.buffer.AbstractReferenceCountedByteBuf"
    "--initialize-at-run-time=io.netty.buffer.UnpooledByteBufAllocator"
    "--initialize-at-run-time=io.netty.buffer.Unpooled"
    "--initialize-at-run-time=io.netty.handler.codec.http.HttpObjectAggregator"
    "--initialize-at-run-time=io.netty.handler.codec.ReplayingDecoderByteBuf"
    "--initialize-at-run-time=io.netty.buffer.ByteBufUtil\$HexUtil"
    "--initialize-at-run-time=io.netty.buffer.PooledByteBufAllocator"
    "--initialize-at-run-time=io.netty.buffer.ByteBufAllocator"
    "--initialize-at-run-time=io.netty.buffer.ByteBufUtil"
    "--initialize-at-run-time=io.netty.handler.codec.compression.BrotliOptions"
    "--initialize-at-run-time=io.netty.handler.codec.compression.ZstdConstants"
    "--initialize-at-run-time=io.netty.handler.codec.compression.ZstdOptions"
    "--initialize-at-run-time=io.vertx.ext.web.handler.sockjs.impl.XhrTransport"
)

LAYERED_NATIVE_ARGS=(
    "--initialize-at-build-time=\"\""
    "-H:LayerCreate=libquarkusbaselayer.nil,module=java.base,module=jdk.localedata,package=io.quarkus.*,package=io.netty.*,package=io.vertx.*,package=jakarta.*"
    "-cp" "getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/*"
    "-o" "libquarkusbaselayer"
    "-H:Path=./target"
)

TRACE_NATIVE_ARGS=(
    "--trace-object-instantiation=org.slf4j.impl.Slf4jLogger"
#    "--trace-object-instantiation=io.netty.util.internal.RefCnt"
)

"$GRAALVM_HOME"/bin/native-image "${BASE_NATIVE_ARGS[@]}" "${TRACE_NATIVE_ARGS[@]}" "${RUN_INIT_NATIVE_ARGS[@]}" "${LAYERED_NATIVE_ARGS[@]}"
