default: run

include ../make/common/MakeBase.gmk
include ../make/common/Maven.gmk
include ../make/common/QuarkusApp.gmk

extensions := resteasy-reactive,hibernate-orm-panache,jdbc-postgresql,smallrye-openapi
java_home := /opt/graalvm-ce-java17-22.3.0
quarkus_version := 2.16.4.Final
